"use client";

import { useEffect, useState, useRef, useId } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { track } from "@/lib/mixpanel";
import CustomSelect from "@/components/ui/CustomSelect";

function FAQItem({ question, answer }: { question: string; answer: string }) {
  const [isOpen, setIsOpen] = useState(false);
  const id = useId();
  const questionId = `faq-question-${id}`;
  const answerId = `faq-answer-${id}`;

  return (
    <div className="group bg-surface-container-low border border-outline-variant/15 hover:border-outline-variant/40 rounded-2xl overflow-hidden hover:bg-surface-container transition-all duration-300">
      <button
        onClick={() => setIsOpen(!isOpen)}
        aria-expanded={isOpen}
        aria-controls={answerId}
        className="w-full flex items-center justify-between p-6 text-left cursor-pointer transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/50 focus-visible:ring-inset rounded-t-2xl"
      >
        <span id={questionId} className="font-bold text-on-surface text-base md:text-lg pr-4">{question}</span>
        <span
          className={`flex-shrink-0 w-8 h-8 rounded-full bg-surface-container-highest group-hover:bg-primary-container group-hover:text-on-primary-container flex items-center justify-center text-on-surface-variant transition-all duration-300 ${
            isOpen ? "rotate-180 bg-primary-container text-on-primary-container" : ""
          }`}
        >
          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" strokeWidth={2.5} stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5" />
          </svg>
        </span>
      </button>
      <div
        id={answerId}
        role="region"
        aria-labelledby={questionId}
        className={`transition-all duration-300 ease-in-out overflow-hidden ${
          isOpen ? "max-h-[500px] opacity-100" : "max-h-0 opacity-0"
        }`}
      >
        <div className="p-6 text-on-surface-variant text-sm md:text-base leading-relaxed border-t border-outline-variant/10">
          {answer}
        </div>
      </div>
    </div>
  );
}

export default function Home() {
  const router = useRouter();
  const [pricingCycle, setPricingCycle] = useState<"monthly" | "yearly">("monthly");
  const [stressor, setStressor] = useState("");
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const [durationMins, setDurationMins] = useState(3);
  const [voice, setVoice] = useState("gentle_female");
  const [music, setMusic] = useState("none");

  const suggestions = [
    "Pitch deck due tomorrow",
    "Can't focus, keep checking phone",
    "Feeling overwhelmed",
    "Procrastinating on hard task",
    "Imposter syndrome",
    "Exam & interview anxiety",
  ];

  const faqs = [
    {
      question: "Who is Unblock built for?",
      answer:
        "Unblock is built for founders, developers, writers, students, creators, and professionals who struggle with task initiation, overthinking, or procrastination. If you frequently find yourself staring at a blank screen or putting off important work, Unblock is for you.",
    },
    {
      question: "How does Unblock help me start working?",
      answer:
        "If you're feeling stuck, overwhelmed, or anxious about a task, Unblock helps you get unstuck. First, you type what's bothering you, and we build a short 2-to-10 minute guided session to clear your mind. Right after, we start a focus session to help you get straight into deep work.",
    },
    {
      question: "Are the guided sessions pre-recorded?",
      answer:
        "No. Every guided session is generated by AI specifically for the situation you describe (like \"worried about a presentation tomorrow\"). Because each session is created uniquely for you rather than played from a static library, wording may vary. If a session doesn't quite resonate, you can simply generate a new one anytime.",
    },
    {
      question: "Is my data private and secure?",
      answer:
        "Yes. Your stressors, tasks, and history are kept completely private and secure in your account. We never share them with anyone.",
    },
    {
      question: "Why are guided sessions kept under 10 minutes?",
      answer:
        "Because the goal is action, not productive procrastination. If your mind is asking for a 30-minute meditation, that is often a subtle delay tactic. Unblock guided sessions are intentionally 2 to 10 minutes to clear your mental blocker fast and get you straight into work with high energy.",
    },
    {
      question: "Does Unblock work on mobile and tablet?",
      answer:
        "Yes! Unblock runs seamlessly in any web browser on Mac, Windows, iPhone, Android, or iPad—no app store download required. You can reset your mind on your phone before sitting down at your desk.",
    },
  ];

  useEffect(() => {
    track("home_page_viewed");
  }, []);

  const handleGetUnblocked = (e: React.FormEvent) => {
    e.preventDefault();
    if (!stressor.trim()) return;

    // Save pending session config to localStorage
    const pendingSession = {
      stressor: stressor.trim(),
      durationMins,
      voice,
      music,
    };
    localStorage.setItem("pending_stressor_session", JSON.stringify(pendingSession));

    router.push("/focus");
  };

  const handleScrollToHero = (e: React.MouseEvent) => {
    e.preventDefault();
    document.getElementById("hero")?.scrollIntoView({ behavior: "smooth" });
  };

  return (
    <div className="min-h-screen flex flex-col">
      {/* ===== Header ===== */}
      <header className="fixed top-0 left-0 right-0 z-50 bg-background/80 backdrop-blur-xl">
        <div className="max-w-7xl mx-auto px-6 md:px-12 h-16 flex items-center justify-between">
          <Link
            href="/"
            className="text-xl font-bold tracking-tighter text-primary-container hover:opacity-80 transition-opacity"
          >
            Unblock
          </Link>
          <nav className="hidden md:flex items-center gap-8">
            <a
              href="#protocol"
              className="text-sm font-medium text-on-surface-variant hover:text-on-surface transition-colors duration-300"
            >
              How it works
            </a>
            <a
              href="#features"
              className="text-sm font-medium text-on-surface-variant hover:text-on-surface transition-colors duration-300"
            >
              Features
            </a>
            <a
              href="#pricing"
              className="text-sm font-medium text-on-surface-variant hover:text-on-surface transition-colors duration-300"
            >
              Pricing
            </a>
            <a
              href="mailto:support@unblockfocus.com"
              className="text-sm font-medium text-on-surface-variant hover:text-on-surface transition-colors duration-300"
            >
              Contact
            </a>
          </nav>
          <div className="flex items-center gap-3">
            <Link
              href="/focus"
              className="text-sm font-medium text-on-surface-variant hover:text-on-surface transition-colors duration-300"
            >
              Sign in
            </Link>
          </div>
        </div>
      </header>

      {/* ===== Hero Section ===== */}
      <main className="flex-1">
        <section id="hero" className="pt-24 pb-12 md:pt-32 md:pb-20 px-6 md:px-12 max-w-7xl mx-auto">
          <div className="flex flex-col items-center text-center max-w-3xl mx-auto space-y-6 md:space-y-10">
            {/* Center: Copy */}
            <div className="space-y-6 flex flex-col items-center">
              {/* Badge */}
              <div className="mb-4 inline-flex items-center gap-2 md:gap-2.5 px-3 md:px-4 py-1 md:py-1.5 rounded-full bg-surface-container-high/60 border border-primary/25 text-on-surface text-[11px] md:text-xs font-medium tracking-wide backdrop-blur-md shadow-sm hover:border-primary/40 transition-colors">
                <span className="relative flex h-2 w-2 shrink-0">
                  <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-primary-container opacity-75"></span>
                  <span className="relative inline-flex rounded-full h-2 w-2 bg-primary-container"></span>
                </span>
                <span>Get unblocked in under 5 minutes</span>
              </div>

              <h1 className="text-5xl md:text-7xl font-bold tracking-tighter text-on-surface leading-[1.05]">
                Break the loop.
                <br />
                <span className="text-primary-container">Get to work.</span>
              </h1>

              <p className="text-on-surface-variant text-lg md:text-xl max-w-2xl mx-auto leading-relaxed">
                Can&apos;t start? Tell us what&apos;s blocking you. We&apos;ll
                build a personalized guided session to clear your head — then
                get you into deep work.
              </p>
            </div>

            {/* Minimalist Input Card + Example Prompts Below */}
            <form onSubmit={handleGetUnblocked} className="w-full space-y-4 max-w-3xl mx-auto text-left pt-2">
              {/* Primary Input Card */}
              <div className="bg-surface-container-low/90 backdrop-blur-xl border border-outline-variant/20 hover:border-outline-variant/35 focus-within:border-primary/50 focus-within:ring-1 focus-within:ring-primary/20 focus-within:shadow-[0_0_30px_rgba(255,130,60,0.12)] rounded-3xl p-5 md:p-6 space-y-4 transition-all shadow-2xl">
                <textarea
                  ref={textareaRef}
                  value={stressor}
                  onChange={(e) => setStressor(e.target.value)}
                  placeholder="e.g. Can't focus, pitch deck panic, feeling overwhelmed..."
                  rows={3}
                  className="w-full bg-transparent border-none p-1 text-sm focus:outline-none text-on-surface placeholder:text-on-surface-variant/40 resize-none leading-relaxed"
                />

                {/* Bottom Toolbar Row: 3 Option Pills (Left) + Action CTA (Right) */}
                <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-3 pt-2">
                  {/* Left Side: Individual Option Selectors */}
                  <div className="flex flex-nowrap sm:flex-wrap items-center gap-2">
                    <CustomSelect
                      className="min-w-0 shrink sm:shrink-0"
                      size="sm"
                      icon="⏱️"
                      value={durationMins > 5 ? "deep" : "quick"}
                      onChange={(val) => setDurationMins(val === "deep" ? 7 : 3)}
                      options={[
                        { value: "quick", label: "Quick (2–5 min)" },
                        { value: "deep", label: "Deep (5–10 min)" },
                      ]}
                    />

                    <CustomSelect
                      className="min-w-0 shrink sm:shrink-0"
                      size="sm"
                      icon="🎙️"
                      value={voice}
                      onChange={setVoice}
                      options={[
                        { value: "gentle_female", label: "Calm" },
                        { value: "soft_male", label: "Steady" },
                      ]}
                    />

                    <CustomSelect
                      className="min-w-0 shrink sm:shrink-0"
                      size="sm"
                      icon="🎵"
                      value={music}
                      onChange={setMusic}
                      options={[
                        { value: "none", label: "Voice Only" },
                        { value: "meditation_impromptu", label: "Ambient Synth" },
                        { value: "flute", label: "Serene Flute" },
                      ]}
                    />
                  </div>

                  {/* Right Side: Capsule Action Button */}
                  <button
                    type="submit"
                    disabled={!stressor.trim()}
                    className={`px-6 py-2.5 rounded-full text-xs font-bold flex items-center justify-center gap-2 transition-all shrink-0 cursor-pointer ${
                      !stressor.trim()
                        ? "bg-surface-container-highest/80 text-on-surface-variant/40 border border-outline-variant/10 cursor-not-allowed"
                        : "bg-[#FF8C53] hover:bg-[#FF7A38] text-slate-950 font-bold shadow-md hover:scale-[1.02] active:scale-95"
                    }`}
                  >
                    ⚡ Get Unblocked
                  </button>
                </div>
              </div>

              {/* Example Prompts Centered Below Card */}
              <div className="text-center pt-1">
                <div className="flex flex-wrap items-center justify-center gap-2">
                  {suggestions.map((s, i) => (
                    <button
                      key={s}
                      type="button"
                      onClick={() => {
                        setStressor(s);
                        textareaRef.current?.focus();
                      }}
                      className={`text-xs px-3.5 py-1.5 rounded-full bg-surface-container-low/50 hover:bg-surface-container-low text-on-surface-variant/80 hover:text-on-surface transition-all cursor-pointer border border-outline-variant/10 hover:border-outline-variant/30 shadow-xs${i >= 3 ? " hidden sm:inline-flex" : ""}`}
                    >
                      {s}
                    </button>
                  ))}
                </div>
              </div>
            </form>
          </div>
        </section>

        {/* ===== Protocol Section ===== */}
        <section
          id="protocol"
          className="py-20 md:py-28 px-6 md:px-12 max-w-7xl mx-auto"
        >
          <div className="text-center max-w-3xl mx-auto mb-16 space-y-4">
            <h2 className="text-3xl md:text-4xl font-bold tracking-tight text-on-surface">
              How it works
            </h2>
            <p className="text-on-surface-variant text-base md:text-lg">
              Three simple steps to break through procrastination and get straight to work.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {/* Step 1 */}
            <div className="bg-surface-container-low border border-outline-variant/15 rounded-2xl p-8 group hover:bg-surface-container hover:border-outline-variant/30 transition-all duration-300 flex flex-col">
              <div className="flex items-center justify-between mb-6">
                <span className="text-[10px] font-bold uppercase tracking-widest text-primary px-2.5 py-1 rounded-full bg-primary/10 border border-primary/20">
                  Step 01
                </span>
                <div className="w-10 h-10 rounded-xl bg-surface-container-highest flex items-center justify-center text-primary group-hover:scale-105 transition-transform">
                  <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10" />
                  </svg>
                </div>
              </div>
              <h3 className="text-lg font-bold text-on-surface mb-3">
                Describe Your Mental Block
              </h3>
              <p className="text-on-surface-variant text-sm leading-relaxed flex-1">
                Type the exact obstacle in front of you—whether it&apos;s pitch deck panic, exam anxiety, or phone distraction. No generic templates.
              </p>
            </div>

            {/* Step 2 */}
            <div className="bg-surface-container-low border border-outline-variant/15 rounded-2xl p-8 group hover:bg-surface-container hover:border-outline-variant/30 transition-all duration-300 flex flex-col">
              <div className="flex items-center justify-between mb-6">
                <span className="text-[10px] font-bold uppercase tracking-widest text-primary px-2.5 py-1 rounded-full bg-primary/10 border border-primary/20">
                  Step 02
                </span>
                <div className="w-10 h-10 rounded-xl bg-surface-container-highest flex items-center justify-center text-primary group-hover:scale-105 transition-transform">
                  <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904 9 18.75l-.813-2.846a4.5 4.5 0 0 0-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 0 0 3.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 0 0 3.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 0 0-3.09 3.09ZM18.259 8.715 18 9.75l-.259-1.035a3.375 3.375 0 0 0-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 0 0 2.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 0 0 2.456 2.456L21.75 6l-1.035.259a3.375 3.375 0 0 0-2.456 2.456ZM16.894 20.567 16.5 21.75l-.394-1.183a2.25 2.25 0 0 0-1.423-1.423L13.5 18.75l1.183-.394a2.25 2.25 0 0 0 1.423-1.423l.394-1.183.394 1.183a2.25 2.25 0 0 0 1.423 1.423l1.183.394-1.183.394a2.25 2.25 0 0 0-1.423 1.423Z" />
                  </svg>
                </div>
              </div>
              <h3 className="text-lg font-bold text-on-surface mb-3">
                3 to 5 Minute Guided Reset
              </h3>
              <p className="text-on-surface-variant text-sm leading-relaxed flex-1">
                Listen to a personalized audio reset generated for your situation—combining targeted breathing and mindset reframes to clear anxiety.
              </p>
            </div>

            {/* Step 3 */}
            <div className="bg-surface-container-low border border-outline-variant/15 rounded-2xl p-8 group hover:bg-surface-container hover:border-outline-variant/30 transition-all duration-300 flex flex-col">
              <div className="flex items-center justify-between mb-6">
                <span className="text-[10px] font-bold uppercase tracking-widest text-primary px-2.5 py-1 rounded-full bg-primary/10 border border-primary/20">
                  Step 03
                </span>
                <div className="w-10 h-10 rounded-xl bg-surface-container-highest flex items-center justify-center text-primary group-hover:scale-105 transition-transform">
                  <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" d="m3.75 13.5 10.5-11.25L12 10.5h8.25L9.75 21.75 12 13.5H3.75Z" />
                  </svg>
                </div>
              </div>
              <h3 className="text-lg font-bold text-on-surface mb-3">
                Timed Deep Work
              </h3>
              <p className="text-on-surface-variant text-sm leading-relaxed flex-1">
                Transition seamlessly into a timed focus session with the Stay-Focused Guard keeping your momentum on track when motivation dips.
              </p>
            </div>
          </div>
        </section>

        {/* ===== Features Section ===== */}
        <section
          id="features"
          className="py-20 md:py-28 px-6 md:px-12 max-w-7xl mx-auto"
        >
          <div className="text-center max-w-3xl mx-auto mb-16 space-y-4">
            <h2 className="text-3xl md:text-4xl font-bold tracking-tight text-on-surface">
              Built for Deep Work
            </h2>
            <p className="text-on-surface-variant text-base md:text-lg">
              Everything you need to clear mental friction, start working, and stay consistent.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {/* Feature 1 */}
            <div className="bg-surface-container-low border border-outline-variant/15 rounded-2xl p-8 hover:bg-surface-container hover:border-outline-variant/30 transition-all duration-300">
              <div className="w-10 h-10 rounded-xl bg-surface-container-highest flex items-center justify-center mb-6 text-primary">
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904 9 18.75l-.813-2.846a4.5 4.5 0 0 0-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 0 0 3.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 0 0 3.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 0 0-3.09 3.09ZM18.259 8.715 18 9.75l-.259-1.035a3.375 3.375 0 0 0-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 0 0 2.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 0 0 2.456 2.456L21.75 6l-1.035.259a3.375 3.375 0 0 0-2.456 2.456ZM16.894 20.567 16.5 21.75l-.394-1.183a2.25 2.25 0 0 0-1.423-1.423L13.5 18.75l1.183-.394a2.25 2.25 0 0 0 1.423-1.423l.394-1.183.394 1.183a2.25 2.25 0 0 0 1.423 1.423l1.183.394-1.183.394a2.25 2.25 0 0 0-1.423 1.423Z" />
                </svg>
              </div>
              <h3 className="text-lg font-bold text-on-surface mb-3">
                Built for Your Situation
              </h3>
              <p className="text-on-surface-variant text-sm leading-relaxed">
                Tell the app what&apos;s blocking you. Get a custom audio reset designed for your exact obstacle—deadlines, burnout, or feeling overwhelmed.
              </p>
            </div>

            {/* Feature 2 */}
            <div className="bg-surface-container-low border border-outline-variant/15 rounded-2xl p-8 hover:bg-surface-container hover:border-outline-variant/30 transition-all duration-300">
              <div className="w-10 h-10 rounded-xl bg-surface-container-highest flex items-center justify-center mb-6 text-secondary">
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M12 3v2.25m6.364.386-1.591 1.591M21 12h-2.25m-.386 6.364-1.591-1.591M12 18.75V21m-4.773-4.23-1.591 1.591M5.25 12H3m4.23-4.773L5.636 5.636M15.75 12a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0Z" />
                </svg>
              </div>
              <h3 className="text-lg font-bold text-on-surface mb-3">
                Guided Breathing Exercises
              </h3>
              <p className="text-on-surface-variant text-sm leading-relaxed">
                Calm physical anxiety in minutes. Smooth breathing animations guide you to lower your heart rate and settle your mind before work.
              </p>
            </div>

            {/* Feature 3 */}
            <div className="bg-surface-container-low border border-outline-variant/15 rounded-2xl p-8 hover:bg-surface-container hover:border-outline-variant/30 transition-all duration-300">
              <div className="w-10 h-10 rounded-xl bg-surface-container-highest flex items-center justify-center mb-6 text-tertiary">
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" d="m3.75 13.5 10.5-11.25L12 10.5h8.25L9.75 21.75 12 13.5H3.75Z" />
                </svg>
              </div>
              <h3 className="text-lg font-bold text-on-surface mb-3">
                Distraction-Free Focus Timer
              </h3>
              <p className="text-on-surface-variant text-sm leading-relaxed">
                Jump straight into work. Transition seamlessly from your reset into a timed focus session to build momentum without distraction.
              </p>
            </div>

            {/* Feature 4 */}
            <div className="bg-surface-container-low border border-outline-variant/15 rounded-2xl p-8 hover:bg-surface-container hover:border-outline-variant/30 transition-all duration-300">
              <div className="w-10 h-10 rounded-xl bg-surface-container-highest flex items-center justify-center mb-6 text-primary">
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" d="M15.362 5.214A8.252 8.252 0 0 1 12 21 8.25 8.25 0 0 1 6.038 7.047 8.287 8.287 0 0 0 9 9.601a8.983 8.983 0 0 1 3.361-6.867 8.21 8.21 0 0 0 3 2.48Z" />
                  <path strokeLinecap="round" strokeLinejoin="round" d="M12 18a3.75 3.75 0 0 0 .495-7.468 5.99 5.99 0 0 0-1.925 3.547 5.975 5.975 0 0 1-2.133-1.001A3.75 3.75 0 0 0 12 18Z" />
                </svg>
              </div>
              <h3 className="text-lg font-bold text-on-surface mb-3">
                Habit & Streak Tracking
              </h3>
              <p className="text-on-surface-variant text-sm leading-relaxed">
                Build daily consistency. Track your focus streaks, completed sessions, and total deep work hours in your personal dashboard.
              </p>
            </div>
          </div>
        </section>

        {/* ===== Testimonials Section ===== */}
        <section
          id="testimonials"
          className="py-20 md:py-28 px-6 md:px-12 max-w-7xl mx-auto"
        >
          <div className="text-center max-w-3xl mx-auto mb-16 space-y-4">
            <h2 className="text-3xl md:text-4xl font-bold tracking-tight text-on-surface">
              Loved by people who hate procrastinating
            </h2>
            <p className="text-on-surface-variant text-base md:text-lg">
              See how others break mental friction and get straight to work.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {/* Testimonial 1 */}
            <div className="bg-surface-container-low border border-outline-variant/15 rounded-2xl p-8 hover:bg-surface-container hover:border-outline-variant/30 transition-all duration-300 flex flex-col justify-between space-y-6">
              <div className="space-y-4">
                {/* 5-star rating */}
                <div className="flex items-center gap-1 text-primary">
                  {[...Array(5)].map((_, i) => (
                    <svg key={i} className="w-4 h-4 fill-current" viewBox="0 0 20 20">
                      <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                    </svg>
                  ))}
                </div>
                <p className="text-on-surface-variant text-sm leading-relaxed">
                  &ldquo;I used to waste hours overthinking pitch decks and investor updates. A 3-minute reset clears the anxiety so I can just sit down and finish what used to take me days.&rdquo;
                </p>
              </div>

              <div className="flex items-center gap-3 pt-4 border-t border-outline-variant/10">
                <div className="w-10 h-10 rounded-full bg-gradient-to-br from-primary/20 to-primary-container/30 border border-primary/30 flex items-center justify-center font-bold text-xs text-primary-container">
                  AC
                </div>
                <div>
                  <h3 className="text-sm font-bold text-on-surface">Alex Chen</h3>
                  <p className="text-xs text-on-surface-variant/70">Founder & Entrepreneur</p>
                </div>
              </div>
            </div>

            {/* Testimonial 2 */}
            <div className="bg-surface-container-low border border-outline-variant/15 rounded-2xl p-8 hover:bg-surface-container hover:border-outline-variant/30 transition-all duration-300 flex flex-col justify-between space-y-6">
              <div className="space-y-4">
                {/* 5-star rating */}
                <div className="flex items-center gap-1 text-primary">
                  {[...Array(5)].map((_, i) => (
                    <svg key={i} className="w-4 h-4 fill-current" viewBox="0 0 20 20">
                      <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                    </svg>
                  ))}
                </div>
                <p className="text-on-surface-variant text-sm leading-relaxed">
                  &ldquo;Whenever I have to start a tricky refactor or dive into a complex codebase, my brain tries to procrastinate. Unblock clears that initial friction so I can jump straight into coding.&rdquo;
                </p>
              </div>

              <div className="flex items-center gap-3 pt-4 border-t border-outline-variant/10">
                <div className="w-10 h-10 rounded-full bg-gradient-to-br from-secondary/20 to-secondary/40 border border-secondary/30 flex items-center justify-center font-bold text-xs text-secondary">
                  MV
                </div>
                <div>
                  <h3 className="text-sm font-bold text-on-surface">Marcus Vance</h3>
                  <p className="text-xs text-on-surface-variant/70">Software Engineer</p>
                </div>
              </div>
            </div>

            {/* Testimonial 3 */}
            <div className="bg-surface-container-low border border-outline-variant/15 rounded-2xl p-8 hover:bg-surface-container hover:border-outline-variant/30 transition-all duration-300 flex flex-col justify-between space-y-6">
              <div className="space-y-4">
                {/* 5-star rating */}
                <div className="flex items-center gap-1 text-primary">
                  {[...Array(5)].map((_, i) => (
                    <svg key={i} className="w-4 h-4 fill-current" viewBox="0 0 20 20">
                      <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                    </svg>
                  ))}
                </div>
                <p className="text-on-surface-variant text-sm leading-relaxed">
                  &ldquo;Staring at a blank document used to lead to hours of research rabbit holes instead of writing. Unblock breaks that initial paralysis so I can actually start drafting.&rdquo;
                </p>
              </div>

              <div className="flex items-center gap-3 pt-4 border-t border-outline-variant/10">
                <div className="w-10 h-10 rounded-full bg-gradient-to-br from-tertiary/20 to-tertiary/40 border border-tertiary/30 flex items-center justify-center font-bold text-xs text-tertiary">
                  SJ
                </div>
                <div>
                  <h3 className="text-sm font-bold text-on-surface">Sarah Jenkins</h3>
                  <p className="text-xs text-on-surface-variant/70">Writer & Researcher</p>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* ===== Pricing Section ===== */}
        <section
          id="pricing"
          className="py-20 md:py-28 px-6 md:px-12 max-w-5xl mx-auto"
        >
          <div className="text-center max-w-3xl mx-auto mb-14 space-y-4">
            <h2 className="text-3xl md:text-4xl font-bold tracking-tight text-on-surface">
              Simple, transparent pricing
            </h2>
            <p className="text-on-surface-variant text-base md:text-lg">
              Start for free. Upgrade when you&apos;re ready to go deeper.
            </p>
          </div>

          {/* Billing Toggle */}
          <div className="flex justify-center mb-10">
            <div className="flex gap-1 bg-surface-container-highest/50 p-1 rounded-xl">
              <button
                onClick={() => setPricingCycle("monthly")}
                className={`px-5 py-2.5 rounded-lg text-xs font-bold uppercase tracking-wider transition-all ${
                  pricingCycle === "monthly"
                    ? "bg-surface-container-low text-on-surface shadow-sm"
                    : "text-on-surface-variant hover:text-on-surface"
                }`}
              >
                Monthly
              </button>
              <button
                onClick={() => setPricingCycle("yearly")}
                className={`px-5 py-2.5 rounded-lg text-xs font-bold uppercase tracking-wider transition-all flex items-center gap-1.5 ${
                  pricingCycle === "yearly"
                    ? "bg-surface-container-low text-on-surface shadow-sm"
                    : "text-on-surface-variant hover:text-on-surface"
                }`}
              >
                Yearly
                <span className="text-[9px] px-1.5 py-0.5 rounded-full bg-primary/15 text-primary font-bold normal-case">
                  Save 43%
                </span>
              </button>
            </div>
          </div>

          {/* Pricing Cards */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 max-w-4xl mx-auto">
            {/* Free Plan */}
            <div className="bg-surface-container-low border border-outline-variant/15 rounded-3xl p-8 md:p-10 flex flex-col">
              <div className="mb-8">
                <p className="text-[10px] font-bold uppercase tracking-widest text-on-surface-variant/60 mb-3">
                  Free
                </p>
                <div className="flex items-baseline gap-1">
                  <span className="text-4xl font-bold text-on-surface">$0</span>
                </div>
                <p className="text-on-surface-variant text-sm mt-3">
                  Perfect for trying Unblock and building your first focus habit.
                </p>
              </div>
              <div className="space-y-3.5 mb-8 flex-1">
                {[
                  "3 AI guided sessions (one-time)",
                  "15 & 25 min focus timers",
                  "Box Breathing technique",
                  "3 most recent session replays",
                  "Habit tracking & streaks",
                  "Session history & stats",
                ].map((feature) => (
                  <div key={feature} className="flex items-center gap-3">
                    <div className="w-5 h-5 rounded-full bg-on-surface-variant/10 flex items-center justify-center shrink-0">
                      <svg className="w-3 h-3 text-on-surface-variant" fill="none" viewBox="0 0 24 24" strokeWidth={3} stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" d="m4.5 12.75 6 6 9-13.5" />
                      </svg>
                    </div>
                    <span className="text-sm text-on-surface-variant">{feature}</span>
                  </div>
                ))}
              </div>
              <Link
                href="/focus"
                className="w-full py-3.5 rounded-xl text-sm font-bold border border-outline-variant/20 text-on-surface hover:bg-surface-container-highest/50 transition-all text-center"
              >
                Get started free
              </Link>
            </div>

            {/* Pro Plan */}
            <div className="bg-surface-container-low border-2 border-primary/30 rounded-3xl p-8 md:p-10 flex flex-col relative overflow-hidden">
              {/* Subtle gradient highlight */}
              <div className="absolute inset-0 bg-gradient-to-br from-primary/5 via-transparent to-secondary/3 pointer-events-none" />
              <div className="relative z-10 flex flex-col flex-1">
                <div className="mb-8">
                  <div className="flex items-center gap-2 mb-3">
                    <p className="text-[10px] font-bold uppercase tracking-widest text-primary">
                      Pro
                    </p>
                    <span className="text-[9px] font-bold uppercase tracking-wider px-2 py-0.5 rounded-full bg-primary/10 text-primary">
                      Most Popular
                    </span>
                  </div>
                  {pricingCycle === "monthly" ? (
                    <div className="flex items-baseline gap-1">
                      <span className="text-4xl font-bold text-on-surface">$29</span>
                      <span className="text-on-surface-variant text-sm">/ month</span>
                    </div>
                  ) : (
                    <div>
                      <div className="flex items-baseline gap-1">
                        <span className="text-4xl font-bold text-on-surface">$199</span>
                        <span className="text-on-surface-variant text-sm">/ year</span>
                      </div>
                      <p className="text-xs text-on-surface-variant/60 mt-1">
                        That&apos;s just $16.58/mo — less than $0.55/day
                      </p>
                    </div>
                  )}
                  <p className="text-on-surface-variant text-sm mt-3">
                    For people serious about deep work and building lasting focus habits.
                  </p>
                </div>
                <div className="space-y-3.5 mb-8 flex-1">
                  {[
                    "Unlimited guided sessions (fair use)",
                    "All focus durations (45m, 90m, custom)",
                    "Advanced breathing techniques",
                    "Full session archive & replays",
                    "Everything in Free",
                  ].map((feature) => (
                    <div key={feature} className="flex items-center gap-3">
                      <div className="w-5 h-5 rounded-full bg-primary/10 flex items-center justify-center shrink-0">
                        <svg className="w-3 h-3 text-primary" fill="none" viewBox="0 0 24 24" strokeWidth={3} stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" d="m4.5 12.75 6 6 9-13.5" />
                        </svg>
                      </div>
                      <span className="text-sm text-on-surface">{feature}</span>
                    </div>
                  ))}
                </div>
                <a
                  href={`/api/checkout?plan=${pricingCycle === "monthly" ? "pro_monthly" : "pro_yearly"}`}
                  className="w-full glow-button py-3.5 rounded-xl text-sm font-bold text-center block hover:scale-[1.01] active:scale-95 transition-all"
                >
                  Upgrade to Pro
                </a>
              </div>
            </div>
          </div>
        </section>

        {/* ===== FAQ Section ===== */}
        <section
          id="faq"
          className="py-20 md:py-28 px-6 md:px-12 max-w-4xl mx-auto"
        >
          <div className="text-center max-w-3xl mx-auto mb-16 space-y-4">
            <h2 className="text-3xl md:text-4xl font-bold tracking-tight text-on-surface">
              Frequently Asked Questions
            </h2>
            <p className="text-on-surface-variant text-base md:text-lg">
              Everything you need to know about Unblock and how it helps you defeat procrastination.
            </p>
          </div>
          <div className="space-y-4">
            {faqs.map((faq, idx) => (
              <FAQItem key={idx} question={faq.question} answer={faq.answer} />
            ))}
          </div>
        </section>

        {/* ===== Bottom CTA ===== */}
        <section className="py-20 md:py-28 px-6 md:px-12">
          <div className="max-w-3xl mx-auto bg-surface-container-low rounded-3xl p-12 md:p-16 text-center ghost-border relative overflow-hidden">
            {/* Subtle ambient glow */}
            <div className="absolute inset-0 bg-gradient-to-br from-primary-container/5 via-transparent to-secondary-container/5 pointer-events-none" />

            <div className="relative z-10">
              <h2 className="text-4xl md:text-5xl font-bold tracking-tighter text-on-surface mb-2 leading-tight">
                Ready to
              </h2>
              <h2 className="text-4xl md:text-5xl font-bold tracking-tighter text-primary-container mb-8 leading-tight">
                get unstuck?
              </h2>
              <p className="text-on-surface-variant text-lg mb-10 max-w-md mx-auto leading-relaxed">
                Tell us what&apos;s blocking you, clear your head with a short
                guided session, then start a focus session. No complicated setup.
              </p>
              <a
                href="#hero"
                onClick={handleScrollToHero}
                className="glow-button px-10 py-4 rounded-xl text-base font-bold mb-4 inline-flex items-center justify-center cursor-pointer"
              >
                Start Guided Session
              </a>
              <p className="text-[11px] font-bold uppercase tracking-[0.2em] text-on-surface-variant">
                Start for free. No credit card required.
              </p>
            </div>
          </div>
        </section>
      </main>

      {/* ===== Footer ===== */}
      <footer className="border-t border-outline-variant/10">
        <div className="max-w-7xl mx-auto px-6 md:px-12 py-12">
          {/* Top row: Brand (Left) + Nav Links (Middle) */}
          <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-8 mb-8 relative">
            {/* Brand (Left) */}
            <div className="space-y-2">
              <span className="text-lg font-bold tracking-tighter text-primary-container">
                Unblock
              </span>
              <p className="text-xs text-on-surface-variant/50 max-w-xs">
                Break through mental blocks. Get to deep work.
              </p>
            </div>

            {/* Nav Links (Middle) */}
            <nav className="flex items-center gap-8 md:absolute md:left-1/2 md:-translate-x-1/2">
              <a
                href="#protocol"
                className="text-xs font-medium text-on-surface-variant hover:text-on-surface transition-colors duration-300"
              >
                How it works
              </a>
              <a
                href="#features"
                className="text-xs font-medium text-on-surface-variant hover:text-on-surface transition-colors duration-300"
              >
                Features
              </a>
              <a
                href="#pricing"
                className="text-xs font-medium text-on-surface-variant hover:text-on-surface transition-colors duration-300"
              >
                Pricing
              </a>
              <a
                href="mailto:support@unblockfocus.com"
                className="text-xs font-medium text-on-surface-variant hover:text-on-surface transition-colors duration-300"
              >
                Contact
              </a>
            </nav>

            {/* Empty right placeholder for flex balance on desktop */}
            <div className="hidden md:block w-48" />
          </div>

          {/* Gradient Divider */}
          <div className="h-px bg-gradient-to-r from-transparent via-outline-variant/20 to-transparent mb-6" />

          {/* Bottom row: Copyright + Legal Links */}
          <div className="flex flex-col sm:flex-row items-center justify-between gap-4">
            <span className="text-xs text-on-surface-variant/40">
              &copy; 2026 Unblock. All rights reserved.
            </span>
            <div className="flex items-center gap-6">
              <Link
                href="/privacy-policy"
                className="text-xs text-on-surface-variant/50 hover:text-on-surface transition-colors"
              >
                Privacy Policy
              </Link>
              <Link
                href="/tos"
                className="text-xs text-on-surface-variant/50 hover:text-on-surface transition-colors"
              >
                Terms of Service
              </Link>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}
