services:
  unblock-focus-backend:
    build: ../
    container_name: unblock-focus-backend
    ports:
      - "127.0.0.1:8001:8000"
    env_file:
      - ../.env
    volumes:
      - backend_data:/app/data
      - backend_media:/app/media
    restart: unless-stopped
    networks:
      - unblock-network

networks:
  unblock-network:
    driver: bridge

volumes:
  backend_data:
  backend_media:
